version: '3'

services:     
  app-frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: ${NODE_ENV}
    image: next-app
    container_name: next-app
    volumes:
      - .:/app
      - ./app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
    networks:
        - nocontrole-network
networks:
  nocontrole-network:
    driver: bridge
