import { Inter } from '@next/font/google'
import Head from 'next/head'
import apiClientInstance from '../services/api-client/api'
import HomePage from './home/Home'

const inter = Inter({ subsets: ['latin'] })

export default function Home(data: SummaryResponse) {


  return (
    <>
      <Head>
        <title>No controle</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomePage {...data} />
    </>
  )
}

// This gets called on every request
export async function getServerSideProps(ctx: any) {
  try {
    const cookie = ctx.req.headers.cookie;
    if (!cookie) {
      return {
        redirect: {
          destination: '/login',
          permanent: false,
        },
      }
    }


    // Fetch data from external API
    const apiClient = apiClientInstance(ctx);
    const { data } = await apiClient.get('/auth/user/summary');




    // Pass data to the page via props
    return { props: data };

  } catch (error) {
    return {
      redirect: {
        destination: '/',
        permanent: false,
      },
    }
  }
}
